sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: BSuRBq9yTKACahzU8p8A20Gq/B5oUieq0BypflGttLzsKVDQqRD5lwQgXx5gDy/begWjA0TFiLgwMZak5oUHCvPBZAtWWTR/Ng9K0OTAbHUuMF4/0qlIS+dizA3zSgk3lKtYb9ZBZQSnyXBHnPS4ZlrOlNP6+NJc2qHEvcHnqQ6OLrbEyxO2jpjf0wnUs+VOC6nmGngIoh4xa6adW7cHRmkCGJif/1OSM5S9BB+WwRAEMNyVF8Ivu+1PycL1FBhfDRtpOJO6ceBv0aYzi0DcrT00vwKQnfGJ/AmSpRoalSofSOe2pGbiqinT3W2jbLLXGk76NH2FepI/uSG4nO1LifxL+CjIccv4FlxkXOTFBK34AlOZOFO57UuIeF6Yj4oWRGGW1RiAQFndzxR7GPRO8A32BnrQzlgyIj38dGoP80Jfhc0+WjPq3prs8KKN/GKZJQStlppFVM55lWwv9nv7JMF6aatzb0qUZqL0kwmVShV2AtE2IqKZNRPRo7n4yn/p+l87G0o9663kgh0NreQOTDif2g8MaYpHvVx7gy3R6UrEUbZOPqUTrqPkUoP4CrdtX9Q0ejQRQkOIFTpJE5QhxrIJNmy+c7nCf57yQg8YV5r/BlWGXdEGMNFFHL1ntq3mbtq6ZuxJcIwGCR0MKCYIdm8Upor7Bp/EZYkun4JMkVk=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Homo-Sum---Complete_5499
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy